# Simple CPU Emulator

This project implements a **Simple CPU Emulator** in Python.  
It models a small 8-bit CPU with a handful of registers, flags, and opcodes.  
The emulator executes machine code programs that can be generated by the companion [Simple Assembler](./simple_assembler.py).

---

## Features

- **Memory**: 256 bytes, fixed size
- **Registers**:
  - General purpose: `A`, `B`, `C` (8-bit each)
  - Flags: `Z` (zero), `S` (sign), `V` (overflow), `C` (carry)
- **Instruction Pointer** (`ip`): tracks the next instruction
- **Dispatch Table**: each opcode maps to a Python method (see [`opcodes.py`](./opcodes.py))
- **Execution Modes**:
  - **Run full program** until `HLT` or memory end
  - **Step-by-step mode** with interactive menu:
    - `N`: execute next instruction
    - `R`: run until the end
    - `D`: dump full memory
    - `I`: inspect a specific memory location
    - `W`: write to a specific memory location
- **Utility methods**:
  - `read_into_memory(program, start_address=0x00)` to load machine code
  - `memory_dump(start=0x00, end=None)` to print memory contents
  - `display_current_state()` to show registers, flags, and memory at the current IP

---

## Example

### 1. Create a program (machine code)

You can hand-write a program or assemble one with the [Simple Assembler](./simple_assembler.py).

Example program (load constants into registers, add, halt):

```python
program = [
    0x20, 0x05,   # MVI A, 0x05
    0x21, 0x03,   # MVI B, 0x03
    0x02,         # ADD B
    0x3F          # HLT
]
